### ISSUE TITLE
FxxkinHero

### ISSUE THREAD

**Issue by MarkusWo** [FredTungsten/Scripts#4]
I always wondered about your script for the FH FxxkinHero. It doesn't really sync up with the strokes in the vid, and it's not just an issue where I just have to shift everything by x seconds. I can't find any "no-host" versions of it or such so I'm wondering what happened to that script and what version you have based your script on. For reference, the version I have has a duration of 24:05.

**Comment by FredTungsten** [comment]
I seem to have a slightly different version (maybe a different/earlier cut?) with a Duration of 22:57.
Maybe I'll re-sync it to the 24:05 version from PH when I find the time.

**Comment by FredTungsten** [comment]
Done, new Script is "Fap Hero - FxxkinHero (PH Version)"
