### ISSUE TITLE
Cock Hero World Championship 2 script is off by about 8 seconds 12m 32s in

### ISSUE THREAD

**Issue by MarkoJac** [FredTungsten/Scripts#5]

**Comment by FredTungsten** [comment]
I'm guessing you are referring to the PH version? That one is a couple of seconds shorter than the original Milovana release - hence the offset.

**Comment by MarkoJac** [comment]
Ah, I see now that the creator actually changed the video a bit and re-uploaded the edited version. This must be for original, cheers doin' gods work Fred.
