### ISSUE TITLE
Scriptplayer playing in full screen pushes controls off screen

### ISSUE THREAD

**Issue by mument** [FredTungsten/Scripts#6]
I've just upgraded to a 4k monitor and now when I toggle to full screen mode the controls at the bottom go off screen with just under the top half of the controls visible which makes them hard to see and click. Any idea how to fix or what might be causing this?
<img width="814" alt="scriptplayer" src="https://user-images.githubusercontent.com/42491129/76762081-869ef900-6788-11ea-8687-87cdb6052e1c.png">

**Comment by FredTungsten** [comment]
Might be related to Windows DPI Scaling.
https://github.com/FredTungsten/ScriptPlayer/issues/128

(btw.: wrong repository, this one is for scripts)

**Comment by mument** [comment]
Sorry - didn't realise I was on the wrong bit of the site. I'll respond on the thread you indicate. Thanks!
    On Monday, March 16, 2020, 03:19:36 PM GMT, Fred Tungsten <notifications@github.com> wrote:  
 
 


Might be related to Windows DPI Scaling.
FredTungsten/ScriptPlayer#128

(btw.: wrong repository, this one is for scripts)
