### ISSUE TITLE
Corresponding links to each video

### ISSUE THREAD

**Issue by dextergrif** [FredTungsten/Scripts#9]
Was wondering if you have a list of corresponding videos to each of the funscripts in this collection. Some of these are very difficult to search for because nothing really comes up for them, for example "HMV -17."

Was wondering if you had a list of links or at the very least a list of creators for each video that's included. I'm essentially going to use this as a guide to check out new HMVs or PMVs and use the funscripts with them.

I am aware this isn't an ISSUE per se but I'm new to github and this was the only way I could figure out how to ask this question lol.

**Comment by FredTungsten** [comment]
Hi,
I don't want to risk this repository by posting links to porn-sites, but if you google eroscripts, you will find an forum that will have a lot more information on where to find the matching videos (if they still exist - a lot of them got lost in the big pornhub-purge of 2020.

**Comment by dextergrif** [comment]
That's completely understandable. Thanks for sending me in the right direction!
